services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  image-store:
    build: image_store
    ports:
      - "5000:5000"
    volumes:
      - image-uploads:/app/uploads

  app:
    depends_on:
      - postgres
      - image-store
    build: .
    profiles:
      - java-backend
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  postgres-data:
  image-uploads:
